/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './app/components/**/*.{js,vue,ts}',
    './app/layouts/**/*.vue',
    './app/pages/**/*.vue',
    './app/plugins/**/*.{js,ts}',
    './app/app.vue',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e4e2dc',
        'on-surface-variant': '#3f4944',
        'on-surface': '#1b1c18',
        'primary': '#005440',
        'secondary-container': '#fcaa33',
        'surface-container-lowest': '#ffffff',
        'on-background': '#1b1c18',
        'surface-dim': '#dcdad3',
        'on-secondary-fixed': '#2a1700',
        'on-tertiary-container': '#ffd3c6',
        'tertiary-fixed': '#ffdbd0',
        'secondary-fixed-dim': '#ffb95d',
        'surface-bright': '#fbf9f2',
        'on-primary-container': '#9aedcf',
        'background': '#fbf9f2',
        'secondary-fixed': '#ffddb7',
        'surface-tint': '#086b53',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#f3f1ea',
        'tertiary-fixed-dim': '#ffb59e',
        'primary-fixed': '#a0f3d4',
        'on-error': '#ffffff',
        'surface': '#fbf9f2',
        'surface-container': '#f0eee7',
        'surface-container-low': '#f6f4ec',
        'on-tertiary-fixed': '#3a0b00',
        'on-tertiary-fixed-variant': '#852400',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'outline-variant': '#bec9c3',
        'inverse-primary': '#84d6b9',
        'inverse-surface': '#30312c',
        'on-secondary-fixed-variant': '#653e00',
        'tertiary': '#892600',
        'primary-fixed-dim': '#84d6b9',
        'on-secondary-container': '#6b4200',
        'primary-container': '#0f6e56',
        'error': '#ba1a1a',
        'on-primary-fixed-variant': '#00513e',
        'secondary': '#855400',
        'on-primary-fixed': '#002117',
        'on-secondary': '#ffffff',
        'outline': '#6f7a74',
        'tertiary-container': '#ac3b12',
        'surface-container-high': '#eae8e1',
        'surface-variant': '#e4e2dc',
        'on-primary': '#ffffff'
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px'
      }
    },
  },
  plugins: [],
}
